type: vertical-stack
cards:
  - type: horizontal-stack
    title: Hot water mode
    cards:
      - type: custom:button-card
        entity: sensor.nibe_hot_water_comfort_mode
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/47041/set
            payload: '0'
        hold_action:
          action: none
        name: Economy
        show_name: true
        icon: mdi:thermometer-low
        state:
          - value: '0'
            color: limegreen
      - type: custom:button-card
        entity: sensor.nibe_hot_water_comfort_mode
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/47041/set
            payload: '1'
        hold_action:
          action: none
        name: Normal
        show_name: true
        icon: mdi:thermometer
        state:
          - value: '1'
            color: orange
      - type: custom:button-card
        entity: sensor.nibe_hot_water_comfort_mode
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/47041/set
            payload: '2'
        hold_action:
          action: none
        name: Luxury
        show_name: true
        icon: mdi:thermometer-high
        state:
          - value: '2'
            color: orangered
  - type: horizontal-stack
    title: Temporary Hot Water Lux
    cards:
      - type: custom:button-card
        entity: sensor.nibe_temporary_lux
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/48132/set
            payload: '0'
        hold_action:
          action: none
        name: 'Off'
        show_name: true
        icon: mdi:water-thermometer-outline
        state:
          - value: '0'
            color: '#b58e31'
      - type: custom:button-card
        entity: sensor.nibe_temporary_lux
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/48132/set
            payload: '4'
        hold_action:
          action: none
        name: One Time Increase
        show_name: true
        icon: mdi:water-thermometer
        state:
          - value: '4'
            color: '#b58e31'
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: sensor.nibe_temporary_lux
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/48132/set
            payload: '1'
        hold_action:
          action: none
        name: 3h
        show_name: true
        icon: mdi:timer
        state:
          - value: '1'
            color: '#b58e31'
      - type: custom:button-card
        entity: sensor.nibe_temporary_lux
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/48132/set
            payload: '2'
        hold_action:
          action: none
        name: 6h
        show_name: true
        icon: mdi:timer
        state:
          - value: '2'
            color: '#b58e31'
      - type: custom:button-card
        entity: sensor.nibe_temporary_lux
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: homeassistant/nibe/modbus/48132/set
            payload: '3'
        hold_action:
          action: none
        name: 12h
        show_name: true
        icon: mdi:timer
        state:
          - value: '3'
            color: '#b58e31'
